# SPDX-License-Identifier: MIT | Author: Rohit Patil
# cmake/auto_version.cmake
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --always
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE GIT_DESCRIBE
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
else()
    set(GIT_DESCRIBE "unknown")
endif()

file(WRITE "${PROJECT_BINARY_DIR}/project_version.hpp"
"// Auto‑generated by CMake – DO NOT EDIT\n"
"#pragma once\n"
"#define EMBD_TRACE_LOG_VERSION \"${GIT_DESCRIBE}\"\n")
